# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        /:title.html

# Setup
title:            Banana On The Wall
tagline:          'I Pee Really Far'
description:      'I pee really far.'
url:              http://blog.thatboy.me

author:
  name:           'Oda'
  url:            http://blog.thatboy.me

paginate:         5