# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        /:title.html

# Setup
title:            Banana On The Wall
tagline:          'a blog neither on banana nor wall'
description:      'a blog neither on banana nor wall'
url:              http://blog.thatboy.me

author:
  name:           'Oda'
  url:            http://blog.thatboy.me

paginate:         5